### ISSUE TITLE
Make available on PyPI?

### ISSUE THREAD

**Issue by chriskuehl** [russjancewicz/python-kadmin#24]
Hi there,

This project looks really neat -- I'd really like to start using this instead of pexpect+kadmin!

I can't seem to find this module on PyPI, though -- I'm wondering if you've considered uploading it there, or if there's some reason you haven't? It would be a lot easier for us to deploy this across our machines if we could install it via pip.

I'd be happy to help in any way with uploading! Thanks for a really cool module!

**Comment by russjancewicz** [comment]
As of a few minutes ago python-kadmin is available via pip.

**Comment by chriskuehl** [comment]
Awesome, thanks for the quick response and great project! This will make our lives easier.
