### ISSUE TITLE
Disconnecting Sessions

### ISSUE THREAD

**Issue by ahabers** [russjancewicz/python-kadmin#28]
Hi, is there a current way to disconnect kadmin sessions?

**Comment by russjancewicz** [comment]
The kadmin object should automatically close the handle to the database and destroy the context pointer upon deallocation. This will happen once the reference count drops to zero for the object or can be invoked explicitly by calling 'del' on the kadmin object. Are you observing different behaviors?

**Comment by ahabers** [comment]
I am observing different behavior. I've tried deleting the object with del, but the connection persists until the python instance is destroyed.

**Comment by russjancewicz** [comment]
I have gone through the admin init phases and removed additional reference increment calls. These forced the reference count to never drop below 1 and the memory never collected (thus the handles not properly closed). I have noticed this behavior in the past but only on large deployments where file-descriptors become exhausted. 
The master branch is up-to-date with the patch please feel free to pull and test; I will be upgrading the PyPy packages shortly (pending another change in the pipeline).

Thank you for your report.

https://github.com/russjancewicz/python-kadmin/pull/29

**Comment by ahabers** [comment]
Thanks, that certainly solved it.
