### ISSUE TITLE
add principal

### ISSUE THREAD

**Issue by tedx** [russjancewicz/python-kadmin#30]
How would I add a principal with this interface?

**Comment by russjancewicz** [comment]
kadm.ank(princ, passwd)
Or
kadm.add_princ(princ, passwd)

They are simply aliases for one another. Please note that setting the passwd value to None Will result in a randomized password.

I'll be sure to update the docs.

-Russell J. Jancewicz

**Comment by tedx** [comment]
Thanks.

**Comment by russjancewicz** [comment]
The docs have been updated (I had an old branch which needed to be merged).
