### ISSUE TITLE
Support for rename_principal

### ISSUE THREAD

**Issue by moonpatrol** [russjancewicz/python-kadmin#48]
I can't find anything in the source that looks like the implementation for rename_principal. I don't suppose there's any plans to implement that command?

I might be able to write an implementation; does anybody have an idea how much effort that would be and where to start?

**Comment by liam-middlebrook** [comment]
With krb5 you can't rename a principal. The closest thing you'll probably want is to create a new principal and delete the old one (hopefully also changing any references from the old principal to the new one).

**Comment by moonpatrol** [comment]
kdamin has a rename_principal command:
http://web.mit.edu/Kerberos/krb5-1.13/doc/admin/admin_commands/kadmin_local.html#rename-principal

I ended up just doing a system call and using kadmin directly for renames.

**Comment by liam-middlebrook** [comment]
Interesting, TIL. I was trying to do that for something a few months ago and wasn't able to find any resources on it. Thanks!
